# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
jobs:
  include:
    - name: "Roxygen check"
      cache: packages
      r_packages:
        - directlabels
        - gdata
        - ggplot2
        - pedigree
        - Rcpp
        - reshape
        - dplyr
        - RColorBrewer
        - truncnorm
        - knitr
        - rmarkdown
        - testthat
    - r: 3.5
    - r: release
    - r: devel
      after_success:
        - travis_wait 30 Rscript coverage.R
      r_build_args: "--no-build-vignettes"

# Only report coverage for the release version
after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change